### PR TITLE
add app shell + dynamic feed caching

### PR DESCRIPTION
**Pull request by housseindjirdeh**
So we'll need HTTPS first.

This adds App Shell + Dynamic feed caching using [sw-precache](https://github.com/GoogleChrome/sw-precache) as well as a web app manifest file so some nice icons will show when we install the app to our homescreen (+ splash screen for Android).

I set up the configurations for the service worker in `sw-precache-config.js` and I'm currently precaching pretty much all the static assets, including bootstrap and font awesome. The sw file sits at 2.68MB which is kind of large, since the browser needs to load this file as well when we load the app. Without bootstrap/font-awesome it drops down to around 668 MB which is more reasonable. However I think we'll need both those libraries to work offline nicely so I'll need to think about this 🤔

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
Okay so test deployed on [Firebase](https://citii-47b8e.firebaseapp.com/). We just need to get the current app with `https` so it can work (shouldn't be too difficult if we use CloudFlare).

**Comment by lucasbento** [comment]
Wow, this is an awesome PR, would you mind taking a look at this, @djirdehh?

**Comment by djirdehh** [comment]
@lucasbento Yup it looks good to go. Going to work with @housseindjirdeh to redirect my app to `https` and we're going to merge this in :)

**Comment by djirdehh** [comment]
Thanks folks!

**Pull request merged**
