### PR TITLE
A simplify way to write react components

### PR DESCRIPTION
**Pull request by redcom**
- constructor and super are not needed because there is no oop in the application.
- fat arrow locks the context so there is no need to bind it in constructor.
- constructor can go away
- state is a static in this case
- added .editorconfig for consistent tabs/space

### CODE REVIEW

**Comment by redcom** [comment]
merge origin master

**Comment by djirdehh** [comment]
You are amazing @redcom. This is a great PR; will be merging it in end of day today.

**Comment by redcom** [comment]
Have you considered using a server as well? To easy communication with 3rd party API?

**Comment by djirdehh** [comment]
@redcom I've aiming to move my API calls to a server to clean things up as a later step. I've never set up a server with React, any recommendations on simple ways of doing so?

Once again, thanks for all the help :)

**Pull request merged**
